# Site setings
name: 'Miguel Jimenez-Urias'
description: 'Computational Physical Oceanographer'
meta_description: ''
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'profile0.png'
  greetings: "I am a computational physical oceanographer interested in improving our understanding of ocean circulation, through the use of theory, computer simulations and global ocean circulation models. I am currently a postdoctoral fellow at Johns Hopkins University."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://royce.netlify.com/
disqus: 'justgoodthemes'
# mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: mjimen17@jh.edu
# contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
#thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
# twitter: 'justgoodthemes'
# facebook: 'mike.jmnez86'
github: 'Mikejmnez'
# codepen: 'username'
# dribbble: 'username'
# medium: '@username'
# instagram: 'username'
# pinterest: 'username'
# linkedin: 'username'
# producthunt: '@username'
# quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /About
  - text: Research
    url: /research
  - text: Teaching
    url: /teaching
  - text: mjimen17@jh.edu
    url: 

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
